name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      CellsCloudClientId: ${{ secrets.PRODUCTCLIENTID }}
      CellsCloudClientSecret: ${{ secrets.PRODUCTCLIENTSECRET }}
      CellsCloudApiBaseUrl: https://api.aspose.cloud

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Install SDK
      run: mvn -B install -DskipTests --file pom.xml

    - name: Run Examples
      run: mvn -B test --file Examples/pom.xml